steps:
  # Terraform
  - id: 'configure_terraform'
    name: node:10.16.3
    entrypoint: "node"
    args: ["./create_terraform_config.js", "${_TERRAFORM_BUCKET_NAME}"]
    dir: "./scripts"
  - id: 'init_terraform'
    name: hashicorp/terraform:light
    args: ["init"]
    dir: "./terraform"
  - id: 'run_terraform'
    name: hashicorp/terraform:light
    args: ["apply", "-auto-approve",
           "-var", "google_project=$PROJECT_ID",
           "-var", "bucket_name=${_BUCKET_NAME}",
           "-var", "bucket_location=${_BUCKET_LOCATION}",
           "-var", "app_location=${_APP_LOCATION}"]
    dir: "./terraform"

  # Client
  - id: 'prepare_client'
    waitFor: ['run_terraform']
    name: node:10.16.3
    entrypoint: "npm"
    args: ["install"]
    dir: "./client"
  - id: 'configure_client'
    waitFor: ['prepare_client']
    name: node:10.16.3
    entrypoint: "node"
    args: ["./create_client_config.js", "${_GOOGLE_API_KEY}", "${_THEME}"]
    dir: "./scripts"
  - id: 'build_client'
    waitFor: ['configure_client']
    name: node:10.16.3
    entrypoint: "npm"
    args: ["run", "build", "--", "-c", "production", "--output-path=./dist",
           "--i18n-file=./src/locale/messages.${_LANGUAGE}.xlf", "--i18n-locale=${_LANGUAGE}",
           "--deploy-url=https://storage.googleapis.com/${_BUCKET_NAME}/"]
    dir: "./client"
  - id: 'deploy_client'
    waitFor: ['build_client']
    name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./dist", "gs://${_BUCKET_NAME}"]
    dir: "./client"
  - id: 'fix_client_content_types'
    waitFor: ['deploy_client']
    name: gcr.io/cloud-builders/gsutil
    args: ["-m", "setmeta", "-h", "Content-Type:text/javascript", "gs://${_BUCKET_NAME}/**/*.js"]
  - id: 'create_client_cors_config'
    waitFor: ['deploy_client']
    name: node:10.16.3
    entrypoint: "node"
    args: ["./create_client_cors_config.js", "https://$PROJECT_ID.appspot.com"]
    dir: "./scripts"
  - id: 'set_client_cors'
    waitFor: ['create_client_cors_config']
    name: gcr.io/cloud-builders/gsutil
    args: ["cors", "set", "./client_cors.json", "gs://${_BUCKET_NAME}"]
    dir: "./"

  # Server
  - id: 'prepare_server'
    waitFor: ['run_terraform']
    name: node:10.16.3
    entrypoint: "npm"
    args: ["install"]
    dir: "./server"
  - id: 'build_server'
    waitFor: ['prepare_server']
    name: node:10.16.3
    entrypoint: "npm"
    args: ["run", "build"]
    dir: "./server"
  - id: 'copy_server_index'
    waitFor: ['build_server', 'build_client']
    name: node:10.16.3
    entrypoint: "cp"
    args: ["./client/dist/index.html", "./server/build/index.html"]
    dir: "./"
  - id: 'deploy_server'
    waitFor: ['copy_server_index']
    name: gcr.io/cloud-builders/gcloud
    args: ["-q", "app", "deploy"]
    dir: "./server"
