steps:
- id: 'clone-github-repo'
  name: 'gcr.io/cloud-builders/git' 
  args: [ 'clone', 'https://github.com/GoogleCloudPlatform/barnard-language-learning-app.git']

- id: 'test'
  name: ubuntu
  entrypoint: bash
  args:
  - '-c'
  - |
    echo $(pwd)
    echo $(ls)
    
- id: 'test2'
  name: ubuntu
  entrypoint: bash
  dir: 'barnard-language-learning-app'
  args:
  - '-c'
  - |
    echo $(pwd)
    echo $(ls)
  
- id: 'replace-code'
  name: ubuntu
  entrypoint: bash
  args:
  - '-c'
  - |
    sed -i "s/barnard-project/${PROJECT_ID}/g" .firebaserc
    sed -i "s/barnard-project/${PROJECT_ID}/g" ./src/utils/ApiUtils.js
  
- id: 'configure_firebase_object'
  name: node:10.16.3
  entrypoint: "node"
  args: ["./create_config.js",
           "${_API_KEY}",
           "${PROJECT_ID}",
           "${_PROJECT_NUMBER}",
           "${_APP_ID}"]
  dir: "./deploy"

- name: 'gcr.io/$PROJECT_ID/firebase'
  args: [ 'use', '${PROJECT_ID}', '--token', '${_FIREBASE_TOKEN}']

- name: 'gcr.io/cloud-builders/npm'
  dir: 'functions'
  args: ['install']
  
- name: 'gcr.io/$PROJECT_ID/firebase'
  dir: 'functions'
  args: [ 'deploy', '--only', 'functions', '--token', '${_FIREBASE_TOKEN}'] 

- name: 'gcr.io/cloud-builders/npm'
  dir: 'functions'
  args: ['install']

- name: 'gcr.io/$PROJECT_ID/firebase'
  dir: 'functions'
  args: [ 'deploy', '--only', 'functions', '--token', '${_FIREBASE_TOKEN}']

- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']

- id: 'deploy-firebase'
  name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy', '--token', '${_FIREBASE_TOKEN}']
