version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    ports:
      - "4200:4200"
    tty: true
    volumes:
      - ./client:/var/www/app
      - /var/www/app/node_modules/
  server:
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./server:/var/www/server
      - /var/www/server/node_modules/