runtime: nodejs10

handlers:
  - url: /ngsw-worker.js
    static_files: static/ngsw-worker.js
    upload: static/ngsw-worker.js
  - url: /ngsw.json
    static_files: static/ngsw.json
    upload: static/ngsw.json
  - url: /.*
    redirect_http_response_code: 301
    secure: always
    script: auto